NDefines.NGraphics.WEATHER_DISTANCE_CUTOFF = 50
NDefines.NGraphics.WEATHER_DISTANCE_FADE_LENGTH = 400
NDefines.NGraphics.WEATHER_ZOOM_IN_CUTOFF = 1
NDefines.NGraphics.WEATHER_ZOOM_IN_FADE_LENGTH = 220
NDefines.NGraphics.WEATHER_ZOOM_IN_FADE_FACTOR = 0.0
NDefines.NGraphics.WEATHER_PLAYBACK_RATE = 0.25
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_CUTOFF = 400
NDefines.NGraphics.WEATHER_PLAYBACK_RATE_LENGTH = 200

NDefines.NMapIcons.STRATEGIC_AIR_PRIORITY_AIR_MISSION = 290
NDefines.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1500}
NDefines.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {200, 350, 500}

NDefines.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 100
NDefines.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 300
NDefines.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 400
NDefines.NGraphics.MAP_ICONS_STRATEGIC_AREA_HUGE = 250
NDefines.NGraphics.MAP_ICONS_STATE_HUGE = 100
NDefines.NGraphics.MAPICON_GROUP_STRATEGIC_SIZE = 1000
NDefines.NGraphics.MAP_ICONS_GROUP_SPLIT_SELECTED_LIMIT = 10
NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 300
NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 0

NDefines.NGraphics.COMMANDGROUP_PRESET_COLORS_HSV = {
	0.0/360.0, 1.0, 1.0,
	10.0/360.0, 1.0, 1.0,
	60.0/360.0, 1.0, 1.0,
	120.0/360.0, 0.75, 1.0,
	180.0/360.0, 1.0, 1.0,
	235.0/360.0, 1.0, 1.0,
	260.0/360.0, 1.0, 1.0,
	300.0/360.0, 1.0, 1.0,
	330.0/360.0, 0, 1.0
}

NDefines.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 20
NDefines.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 600
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 250.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_A = 250
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 250
NDefines.NGraphics.ROOT_FRONT_OFFSET = 2

NDefines.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.90
NDefines.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.80

NDefines.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 0
NDefines.NAirGfx.MAX_BOMBING_SCENARIOS = 0
NDefines.NAirGfx.MAX_PATROL_SCENARIOS = 0
NDefines.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 0
NDefines.NAirGfx.MAX_TRANSPORT_SCENARIOS = 0
NDefines.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = {0.3, 0.3, 0.3, 0.3, 0.3, 0.3}
NDefines.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_MOVE = 0.02
NDefines.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_TURN = 0.02

NDefines.NMapMode.MAP_MODE_TERRAIN_TRANSPARENCY = 0.8
NDefines.NMapMode.RADAR_ROTATION_SPEED = 0.0
NDefines.NMapMode.AIR_RANGE_INDICATOR_ROTATION_SPEED = 0.0000

NDefines.NMapMode.SUPPLY_MAP_MODE_REACH_COLOR = {
	0.0, 0.45, 0.00, 0.20, 1.0,
	0.02, 0.35, 0.12, 0.45, 1.0,
	0.12, 0.20, 0.15, 0.45, 1.0,
	0.2, 0.27, 0.27, 0.50, 1.0,
	0.4, 0.15, 0.25, 0.40, 1.0,
	0.6, 0.20, 0.42, 0.60, 1.0,
	0.8, 0.35, 0.50, 0.30, 1.0,
	1.0, 0.15, 0.54, 0.15, 1.0
}

NDefines.NGraphics.DECISION_MAP_ICON_DISTANCE_CUTOFF = 1000
NDefines.NGraphics.PROVINCE_ANIM_TEXT_DISTANCE_CUTOFF = 200
NDefines.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 600
NDefines.NGraphics.RADAR_ICON_DISTANCE_CUTOFF = 150
NDefines.NGraphics.MAX_MESHES_LOADED_PER_FRAME = 5
NDefines.NGraphics.RESOURCE_MAP_ICON_TEXT_CUTOFF = 400
NDefines.NGraphics.UNITS_DISTANCE_CUTOFF = 90			-- FPS BOOSTER (was 100): 3D models become 2D counters sooner
NDefines.NGraphics.SHIPS_DISTANCE_CUTOFF = 100			-- FPS BOOSTER (was 200)
NDefines.NGraphics.UNIT_ARROW_DISTANCE_CUTOFF = 500
NDefines.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 700
NDefines.NGraphics.NAVAL_COMBAT_DISTANCE_CUTOFF = 1000
NDefines.NGraphics.ADJACENCY_RULE_DISTANCE_CUTOFF = 1300
NDefines.NGraphics.LAND_COMBAT_DISTANCE_CUTOFF = 800
NDefines.NGraphics.PROV_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 300
NDefines.NGraphics.STATE_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 600
NDefines.NGraphics.DRAW_MAP_OBJECTS_CUTOFF = 1.0

NDefines.NGraphics.MAPICON_GROUP_PASSES = 5
NDefines.NGraphics.DRAW_REFRACTIONS_CUTOFF = 0
NDefines.NGraphics.BLOOM_WIDTH = 0
NDefines.NGraphics.BLOOM_SCALE = 0
NDefines.NGraphics.BRIGHT_THRESHOLD = 0
NDefines.NGraphics.EMISSIVE_BLOOM_STRENGTH = 0
NDefines.NGraphics.DAY_NIGHT_FEATHER = 0.024
NDefines.NGraphics.DRAW_SHADOWS_CUTOFF = 0
NDefines.NGraphics.DRAW_SHADOWS_FADE_LENGTH = 0
NDefines.NGraphics.DRAW_FOW_CUTOFF = 0
NDefines.NGraphics.DRAW_FOW_FADE_LENGTH = 0

NDefines.NGraphics.TREE_FADE_NEAR = 150.0
NDefines.NGraphics.TREE_FADE_FAR = 250.0


-- some spot stuff

NDefines.NGraphics.STRATEGIC_AIR_COLOR_BAD = {0.65, 0, 0, 1}
NDefines.NGraphics.STRATEGIC_AIR_COLOR_GOOD = {0, 0.65, 0, 1}
NDefines.NGraphics.STRATEGIC_AIR_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines.NGraphics.STRATEGIC_AIR_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1}

NDefines.NGraphics.RESISTANCE_COLOR_GOOD = {0.0, 0.65, 0, 1}
NDefines.NGraphics.RESISTANCE_COLOR_AVERAGE = {0.65, 0.65, 0, 1}
NDefines.NGraphics.RESISTANCE_COLOR_BAD = {0.65, 0, 0, 1}

-- MSB graphics defines added
NDefines.NGraphics.GRADIENT_BORDERS_FIELD_COUNTRY_REFRESH = 40
NDefines.NInterface.GRIDBOX_ELEMENTS_INTERPOLATION_SPEED = 0.2
NDefines.NGraphics.SUPPLY_ICON_DISTANCE_CUTOFF = 1500
NDefines.NGraphics.GRADIENT_BORDERS_REFRESH_FREQ = 0.30		-- FPS BOOSTER (was 0.2): borders repaint less often